[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm && pnpm install"]

[phases.build]
cmds = ["npm install -g pnpm && pnpm build --filter api"]

[start]
cmd = "node apps/api/dist/index.js"
